# Generated by Django 2.2 on 2021-02-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210103_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Vendor'),
        ),
    ]
