# Generated by Django 2.2 on 2021-02-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210210_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preference',
            field=models.CharField(blank=True, choices=[('V', 'veg'), ('N', 'non-veg'), ('M', 'mix')], max_length=20, null=True, verbose_name='Food preference'),
        ),
    ]
