# Generated by Django 2.2 on 2021-02-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210210_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='payment_mode',
        ),
    ]
