# Generated by Django 2.2 on 2021-02-15 08:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_vendor_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='payment_mode',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('offline pay', 'COD'), ('online', 'paytym')], default=1, max_length=18),
            preserve_default=False,
        ),
    ]
