# Generated by Django 2.2 on 2021-02-15 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20210210_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(choices=[('M', 'MONTHLY'), ('W', 'WEEKLY'), ('D', 'ONE TIME'), ('F', 'FULL MEAL')], max_length=20, verbose_name='SUB_PLAN')),
                ('subscription_menu', models.CharField(choices=[('Break fast', 'Break fast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subcriptions.Subscription')),
            ],
        ),
    ]
