# Generated by Django 3.1.4 on 2021-01-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(choices=[('M', 'MONTHLY'), ('W', 'WEEKLY'), ('D', 'ONE TIME'), ('F', 'FULL MEAL')], max_length=20, verbose_name='SUB_PLAN')),
                ('subscription_menu', models.CharField(choices=[('Break fast', 'Break fast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ManyToManyField(to='subcriptions.Subscription')),
            ],
        ),
    ]
