# Generated by Django 2.2 on 2021-02-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscription',
            name='subscription',
        ),
    ]
