# Generated by Django 2.2 on 2021-02-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcriptions', '0002_remove_customersubscription_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='subscription',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='subcriptions.Subscription'),
        ),
    ]
