# Generated by Django 2.2 on 2021-02-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcriptions', '0003_auto_20210201_2145'),
        ('subcriptions', '0003_auto_20210202_0829'),
    ]

    operations = [
    ]
